# Información general
site_name: 'Catequesis'
site_description: 'Apuntes sobre la fe católica'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.xyz/catequesis

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/catequesis'

# Copyright
copyright: '2019 &nbsp; Raul Jesus Lopez'

# Tema
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'yellow'
    accent: 'yellow'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  feature:
#    tabs: true

# Extra
extra:
  search:
    language: 'es, en'
  disqus: 'rauljesus-xyz'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
    - type: 'facebook'
      link: 'https://www.facebook.com/rauljesuslopez'
    - type: 'github'
      link: 'https://github.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'

## CSS Adicional
extra_css:
  - 'stylesheets/extra.css'

# Extensiones
markdown_extensions:
  - admonition
#  - codehilite(guess_lang=false,linenums=true)
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'


######################################################################
### DOCUMENTACIÓN ####################################################
######################################################################

# Páginas
nav: 
- Inicio: 'index.md'
- Creemos: 
    - Preguntas fundamentales: 'creemos/hierofanias.md'
    - Razones para creer: 'creemos/las5vias.md'
    - Ley Natural: 'creemos/leynatural.md'
    - Cuestionario: 'creemos/cuestionario.md'
    - Trabajo práctico: 'creemos/trabajoPractico.md'
- Palabra de Dios:
    - Relato de la Creación: 'palabra/genesis.md'
    - Cuestionario Gn: 'palabra/genesisCuestionario.md'
    - Hermenéutica: 'palabra/hermeneutica.md'

